# 3-1 선형 회귀

In [1]:
# 파이토치 기본 셋팅
import torch
import torch.nn as nn
# torch.nn : 신경망을 구축하는 데 필요한 모든 구성 요소를 제공. 이 모듈에는 레이어, 활성화 함수, 손실 함수를 포함

import torch.nn.functional as F
# torch.nn.functional : torch.nn과 마찬가지로 신경망을 구축할 때 사용되는 함수들을 포함하지만, 이 모듈에 있는 함수들은 상태가 없는(stateless) 함수입니다. 즉, 함수들이 내부적으로 학습 파라미터를 가지지 않고, 입력 데이터와 함수에 지정된 파라미터에만 의존하여 결과를 반환

import torch.optim as optim

# torch.optim : 최적화 알고리즘들을 제공합니다. 가중치(weights)와 편향(biases)을 업데이트하는 데 사용되는 다양한 최적화 알고리즘들, 예를 들어 SGD(확률적 경사 하강법), Adam, RMSprop 등이 이 모듈에 포함

In [2]:
# 다음에도 같은 결과가 나오도록 시드를 준다
torch.manual_seed(1)

In [3]:
# 변수 선언 
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [4]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [6]:
# 가중치 W와 편향 b를 설정할 거임
# requires_grad => 학습을 통해 값이 변경되는 변수임을 명시
W  = torch.zeros(1,requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [7]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [8]:
# 가설 세우기
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [9]:
# 손실 함수 정의
loss = torch.mean((hypothesis - y_train) ** 2)
print(loss)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [10]:
# 경사 하강법 구현
# 확률적 경사하강법으로 학습률은 0.01로 학습을 할거임
# [W,b] : 최적화 할 파라미터
optimizer = optim.SGD([W,b],lr=0.01)


In [11]:
# gradient를 0으로 초기화
# 옵티마이저가 관리하는 모델 파라미터에 대한 gradient를 0으로 초기화
# 파이토치에서는 그래디언트가 누적되는 방식으로 계산되기때문에 초기화 해줘야함
optimizer.zero_grad()

# 손실함수를 미분해 gradient를 계산
# 각 가중치에 대해 손실함수를 얼마나 변경해야하는지 gradient를 구함
loss.backward()

# W와 b를 실제로 업데이트하는 단계
optimizer.step()

# requires_grad=True와 backward()에 대한 정리는 
# 자동 미분(Autograd) 챕터에 별도 정리 (5-2)

In [12]:
# 전체 코드

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.353, b: 0.151 Cost: 14.770963
Epoch  100/1999 W: 1.746, b: 0.577 Cost: 0.047939
Epoch  200/1999 W: 1.801, b: 0.453 Cost: 0.029624
Epoch  300/1999 W: 1.843, b: 0.356 Cost: 0.018306
Epoch  400/1999 W: 1.877, b: 0.280 Cost: 0.011312
Epoch  500/1999 W: 1.903, b: 0.220 Cost: 0.006990
Epoch  600/1999 W: 1.924, b: 0.173 Cost: 0.004319
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002669
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001649
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001019
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000630
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000389
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000240
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

In [13]:
# optimizer.zero_grad()가 필요한 이유
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    z = 2*w

    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad))
    
# 아래와 같이 이전에 계산된 기울기값에 gradient를 누적시키기 때문

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


## 5-2 자동 미분 실습

In [14]:
w = torch.tensor(2.0, requires_grad=True)
# 여기서 requires_grad를 True로 두변 w.grad에 대한 미분값이 저장됨

# 함수를 아래와 같이 정의
y = w**2
z = 2*y + 5
# 즉 우리가 미분할 함수는 2 x W^2 +5를 w에 대해 미분할 거임

In [15]:
z.backward()
# 이를 호출하면 해당 수식에서 w에 대한 기울기를 계산함

In [16]:
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


## 3-3 다중 선형 회귀
x가 하나가 아닌, 여러개의 x로 부터 y를 예측하는걸 다중 선형회귀라함


In [17]:
# 훈련 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))


Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563634
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497607
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435026
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375730
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319511
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215696
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167818
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079378


In [18]:
# 행렬연산으로 변환한 다중 선형 회귀

x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  80],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))


Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670898
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.482086
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

## 3-4 nn.Module로 구현하는 선형 회귀
위에선 직접 가설함수와 비용함수를 정의했지만,
이미 구현된 함수로 선형회귀 모델을 구현하기

위에서 사용한 모델
nn.Linear() => 선형 회귀 모델
nn.functional.mse_loss()  => 평균 제곱 오차

구현 예시
import torch.nn as nn
model = nn.Linear(input_dim, output_dim)

import torch.nn.functional as F
cost = F.mse_loss(prediction, y_train)


In [19]:
 # y = 2 * x 즉 W = 2, b = 0 이라는 정답을 아는 상태에서 W와 b 찾기
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

model = nn.Linear(1,1)

In [20]:
list(model.parameters())
# 랜덤으로 구해진 파라밑 값

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [21]:
optimizer = optim.SGD(model.parameters(),lr=0.01)

In [22]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
        # 100번마다 로그 출력
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))


Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [23]:
new_var = torch.FloatTensor([4.0])
pred_y = model(new_var)
print(pred_y)

tensor([7.9989], grad_fn=<ViewBackward0>)


In [24]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [25]:
# 다중 회귀 구현하기
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

In [26]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [27]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
        # 100번마다 로그 출력
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))


Epoch    0/2000 Cost: 42134.707031
Epoch  100/2000 Cost: 5.960053
Epoch  200/2000 Cost: 5.654707
Epoch  300/2000 Cost: 5.365413
Epoch  400/2000 Cost: 5.091429
Epoch  500/2000 Cost: 4.831839
Epoch  600/2000 Cost: 4.585955
Epoch  700/2000 Cost: 4.353065
Epoch  800/2000 Cost: 4.132465
Epoch  900/2000 Cost: 3.923480
Epoch 1000/2000 Cost: 3.725513
Epoch 1100/2000 Cost: 3.537985
Epoch 1200/2000 Cost: 3.360339
Epoch 1300/2000 Cost: 3.192060
Epoch 1400/2000 Cost: 3.032671
Epoch 1500/2000 Cost: 2.881697
Epoch 1600/2000 Cost: 2.738672
Epoch 1700/2000 Cost: 2.603198
Epoch 1800/2000 Cost: 2.474846
Epoch 1900/2000 Cost: 2.353288
Epoch 2000/2000 Cost: 2.238106


In [28]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 


훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.7184]], grad_fn=<AddmmBackward0>)


In [29]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8541, 0.8475, 0.3096]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]


## 3-5 클래스로 파이토치 모델 구현하기

In [30]:
# 위의 모델을 클래스로  그대로 구현하기
# 단순 선형 회귀
class LinearRegressionModel(nn.Module): 
    # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self): #
        super().__init__()
        # 상위 클래스의 생성자를 호출해 초기화 작업 진행
        self.linear = nn.Linear(1, 1) 
        # 단순 선형 회귀이므로 input_dim=1, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [31]:
# 다중 선형 회귀
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)


In [32]:
# 단순 선형회귀 클래스로 구현

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])


model = LinearRegressionModel()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
        # 100번마다 로그 출력
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))


Epoch    0/2000 Cost: 18.474602
Epoch  100/2000 Cost: 0.136136
Epoch  200/2000 Cost: 0.084124
Epoch  300/2000 Cost: 0.051984
Epoch  400/2000 Cost: 0.032123
Epoch  500/2000 Cost: 0.019850
Epoch  600/2000 Cost: 0.012266
Epoch  700/2000 Cost: 0.007580
Epoch  800/2000 Cost: 0.004684
Epoch  900/2000 Cost: 0.002894
Epoch 1000/2000 Cost: 0.001788
Epoch 1100/2000 Cost: 0.001105
Epoch 1200/2000 Cost: 0.000683
Epoch 1300/2000 Cost: 0.000422
Epoch 1400/2000 Cost: 0.000261
Epoch 1500/2000 Cost: 0.000161
Epoch 1600/2000 Cost: 0.000100
Epoch 1700/2000 Cost: 0.000062
Epoch 1800/2000 Cost: 0.000038
Epoch 1900/2000 Cost: 0.000023
Epoch 2000/2000 Cost: 0.000015


In [33]:
var2 = torch.FloatTensor([5])
y_pred = model.forward(var2)
y_pred

tensor([9.9880], grad_fn=<ViewBackward0>)

## 3-6 미니 배치와 배치 크기

전체 데이터 크기 = 미니 배치 크기 X 이터레이션(매개변수 업데이트 횟수)

In [34]:
# 파이토치엔 데이터셋, 데이터로더가 존재
# 미니배치 학습, 데이터 셔플, 병렬 처리까지 수행 가능

from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [35]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  90],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

dataset = TensorDataset(x_train, y_train)


In [36]:
# 미니 배치의 크기는 통상적으로2의 배수를 사용
# shuffle은 에폭마다 데이터셋을 섞어서 학습 순서를 바꿈
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [37]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [38]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        # print(batch_idx)
        # print(samples)
        x_train, y_train = samples
        # H(x) 계산
        prediction = model(x_train)

        # cost 계산
        cost = F.mse_loss(prediction, y_train)

        # cost로 H(x) 계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, batch_idx+1, len(dataloader),
            cost.item()
        ))


Epoch    0/20 Batch 1/3 Cost: 21981.667969
Epoch    0/20 Batch 2/3 Cost: 9587.075195
Epoch    0/20 Batch 3/3 Cost: 3180.415527
Epoch    1/20 Batch 1/3 Cost: 656.754761
Epoch    1/20 Batch 2/3 Cost: 208.265625
Epoch    1/20 Batch 3/3 Cost: 60.448395
Epoch    2/20 Batch 1/3 Cost: 20.464521
Epoch    2/20 Batch 2/3 Cost: 4.721592
Epoch    2/20 Batch 3/3 Cost: 7.182279
Epoch    3/20 Batch 1/3 Cost: 1.647293
Epoch    3/20 Batch 2/3 Cost: 0.378696
Epoch    3/20 Batch 3/3 Cost: 1.522853
Epoch    4/20 Batch 1/3 Cost: 1.254019
Epoch    4/20 Batch 2/3 Cost: 2.134096
Epoch    4/20 Batch 3/3 Cost: 0.052373
Epoch    5/20 Batch 1/3 Cost: 0.230397
Epoch    5/20 Batch 2/3 Cost: 1.461857
Epoch    5/20 Batch 3/3 Cost: 2.749334
Epoch    6/20 Batch 1/3 Cost: 1.041578
Epoch    6/20 Batch 2/3 Cost: 1.587193
Epoch    6/20 Batch 3/3 Cost: 1.168151
Epoch    7/20 Batch 1/3 Cost: 0.446066
Epoch    7/20 Batch 2/3 Cost: 2.133462
Epoch    7/20 Batch 3/3 Cost: 0.879393
Epoch    8/20 Batch 1/3 Cost: 0.129109
Epoch    

In [39]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.9222]], grad_fn=<AddmmBackward0>)


## 커스텀 데이터 셋

데이터셋은 추상클래스여서 상속받아 클래스를 만듬

class CustomDataset(torch.utils.data.Dataset): 
  def __init__(self):
  데이터셋의 전처리를 해주는 부분

  def __len__(self):
  데이터셋의 길이. 즉, 총 샘플의 수를 적어주는 부분

  def __getitem__(self, idx): 
  데이터셋에서 특정 1개의 샘플을 가져오는 함수


In [40]:
# Dataset 상속
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self):
        self.x_data = [[73, 80, 75],
                       [93, 88, 93],
                       [89, 91, 90],
                       [96, 98, 100],
                       [73, 66, 70]]
        self.y_data = [[152], [185], [180], [196], [142]]

    # 총 데이터의 개수를 리턴
    def __len__(self):
        return len(self.x_data)

    # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

In [41]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        # print(batch_idx)
        # print(samples)
        x_train, y_train = samples
        # H(x) 계산
        prediction = model(x_train)

        # cost 계산
        cost = F.mse_loss(prediction, y_train)

        # cost로 H(x) 계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, batch_idx+1, len(dataloader),
            cost.item()
        ))


Epoch    0/20 Batch 1/3 Cost: 29319.011719
Epoch    0/20 Batch 2/3 Cost: 7682.496094
Epoch    0/20 Batch 3/3 Cost: 3114.666504
Epoch    1/20 Batch 1/3 Cost: 809.166870
Epoch    1/20 Batch 2/3 Cost: 300.709198
Epoch    1/20 Batch 3/3 Cost: 37.518616
Epoch    2/20 Batch 1/3 Cost: 37.871822
Epoch    2/20 Batch 2/3 Cost: 3.583100
Epoch    2/20 Batch 3/3 Cost: 15.499701
Epoch    3/20 Batch 1/3 Cost: 3.772459
Epoch    3/20 Batch 2/3 Cost: 2.178463
Epoch    3/20 Batch 3/3 Cost: 0.037612
Epoch    4/20 Batch 1/3 Cost: 0.297060
Epoch    4/20 Batch 2/3 Cost: 2.369325
Epoch    4/20 Batch 3/3 Cost: 2.928090
Epoch    5/20 Batch 1/3 Cost: 1.220521
Epoch    5/20 Batch 2/3 Cost: 1.797108
Epoch    5/20 Batch 3/3 Cost: 1.805746
Epoch    6/20 Batch 1/3 Cost: 0.409884
Epoch    6/20 Batch 2/3 Cost: 2.198062
Epoch    6/20 Batch 3/3 Cost: 2.823555
Epoch    7/20 Batch 1/3 Cost: 1.618690
Epoch    7/20 Batch 2/3 Cost: 1.817710
Epoch    7/20 Batch 3/3 Cost: 2.327748
Epoch    8/20 Batch 1/3 Cost: 2.224390
Epoch   

In [42]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 


훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.6855]], grad_fn=<AddmmBackward0>)
