## 2-1 파이토치 패키지의 기본구성
torch : 
메인 네임스페이스

torch.autograd : 
자동미분을 위한 함수를 포함하고 있음
자동 미분의 on/off를 제어하는 콘텍스트 매니저(enable_grad/no_grad)와
자체 미분을 정의할때 사용하는 Function이 포함됨

torch.nn : 
신경망을 구축하기 위한 다양한 데이터 구조, 레이어가 정의되어 있음
ex) RNN, LSTM 레이어/ ReLU 활성화함수/ MSELoss 손실함수

torch.optim : 
확률적 경사하강법(SGD)을 중심으로한 파라미터 최적화 알고리즘이 구현

torch.utils.data : 
SGD 반복연산 실행시 사용되는 미니배치용 유틸리티 함수가 포함

torch.onnx :
모델을 ONNX 포맷으로 모델을 export할 때 사용
ONNX는 서로 다른 딥러닝 프레임워크 간에 모델을 공유할때 사용


## 2-2 텐서 조작하기

### 1. 벡터 행렬 템서

1차원으로 구성된 값 : 벡터
2차원으로 구성된 값 : 행렬
3차원으로 구성된 값 : 텐서
n차원으로 구성된 값 : n차원 텐서

하지만 데이터 사이언스에서는 1차원부터 그냥 1차원 텐서라 함

### 2. 파이토치 텐서 shape 컨벤션
행렬과 텐션을 앞으로 다음과 같은 표현으로 할 것임
2D Tensor : |t| = (batch size, dim)
2차원 텐서에서 행이 batch size고 열이 dim임
즉 batch size X dim 행렬이라 생각하면 됨

ex) 훈련 데이터 1개 크기 : 256 
3000개의 훈련 데이터가 있다고 하면 
전체 데이터 크기 : 3000 x 256
컴퓨터는 한번에 여러개의 데이터를 처리하므로 
3000개에서 64개씩 꺼내서 처리한다고 하면
2D 텐서의 크기는 64 X 256가 됨

### 3D 텐서 
비전 분야에서의 3D 텐서
|t| = (batch size, width, height)
여기서 width와 height => 사진 1개 가로세로라 생각하면 됨

NLP에서의 3D 텐서
|t| = (batch size, length, dim)
(batch size, 문장길이, 단어 벡터의 차원)으로 사용됨

### NLP분야에서 3D 텐서 예제로 이해 하기
[[나는 사과를 좋아해], [나는 바나나를 좋아해], [나는 사과를 싫어해], [나는 바나나를 싫어해]]
라는 전체 훈련데이터가 있다고 가정하자

이때 컴퓨터는 단어가 몇개인지 인식을 못하므로 단어별로 나눠줘야함
[['나는', '사과를', '좋아해'], ['나는', '바나나를', '좋아해'],
 ['나는', '사과를', '싫어해'], ['나는', '바나나를', '싫어해']]

이렇게되면 훈련데이터는 4 X 3 크기를 갖는 2차원 텐서가 됨

컴퓨터는 텍스트보다 숫자를 잘 처리하므로 각 단어를 벡터로 변환함
'나는' = [0.1, 0.2, 0.9]
'사과를' = [0.3, 0.5, 0.1]
'바나나를' = [0.3, 0.5, 0.2]
'좋아해' = [0.7, 0.6, 0.5]
'싫어해' = [0.5, 0.6, 0.7]

이를 바탕으로 훈련데이터를 재구성하면

[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

이렇게 되면 4X3X3 크기를 갖는 3D 텐서가됨

여기서 배치 크기를 2로 하면
첫번째 배치 #1
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]

두번째 배치 #2
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]
 
이고 각 텐서의 크기는 2X3X3이 됨

## 2. 넘파이로 텐서 만들기

In [1]:
# 1D 텐서 만들기
import numpy as np

t = np.array([1.,2,3,4,5,6])
print(t)

[1. 2. 3. 4. 5. 6.]


In [2]:
print('rank of t :', t.ndim)
print('shape of t :', t.shape)

rank of t : 1
shape of t : (6,)


In [3]:
# 넘파이에서 각 벡터의 원소에 접근하는 방법
print('t[0] t[1] t[-1] = ',t[0] ,t[1], t[-1])

t[0] t[1] t[-1] =  1.0 2.0 6.0


In [4]:
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) 
# [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다.

t[2:5] t[4:-1]  =  [3. 4. 5.] [5.]


In [5]:
# 넘파이로 2D 만들기
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


## 3. 파이토치 텐서 선언하기

In [7]:
# 파이토치 import 하기
import torch

In [8]:
# 파이토치로 1차원 텐서 만들기
t = torch.FloatTensor([1,2,3,4,5,6,7])
print(t)

tensor([1., 2., 3., 4., 5., 6., 7.])


In [9]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape
print(type(t))

1
torch.Size([7])
torch.Size([7])
<class 'torch.Tensor'>


In [10]:
# 넘파이랑 마찬가지로 슬라이싱 하기
print(t[0], t[1], t[2])
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) 

tensor(1.) tensor(2.) tensor(3.)
t[2:5] t[4:-1]  =  tensor([3., 4., 5.]) tensor([5., 6.])


In [11]:
# 파이토치로 2차원 텐서
t = torch.FloatTensor([[1., 2., 3.], [4,5,6]])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [12]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape
print(type(t))

2
torch.Size([2, 3])
<class 'torch.Tensor'>


In [13]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([2., 5.])
torch.Size([2])


In [14]:
# 브로드 캐스팅
# 크기가 다른 행렬 또는 텐서에서 사칙연산해야할 경우
# 자동으로 크기를 맞춰서 연산을 수행하게 만드는 것

# 같은 크기일 때 연산을 하는 경우
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)


tensor([[5., 5.]])


In [15]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [16]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
# [1 2]
# [1 2]

m2 = torch.FloatTensor([[3], [4]])
# [3 3]
# [4 4]

print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## 4. 자주 사용되는 기능
### 1. 행렬 곱셈과 곱셈의 차이
행렬곱셉(.matmul)과 원소별 곱셈(.mul)의 차이에 대해 알아야함

In [17]:
# 텐서의 행렬 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [18]:
# 원소별 곱셈
# 원소별 곱셈은 *를 이용하거나 .mul 함수를 사용하면 됨
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 2. mean() 함수

In [19]:
# 1차원 벡터의 원소의 평균 구하기
t = torch.FloatTensor([1, 2])
t.mean()

tensor(1.5000)

In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [21]:
# 차원을 기준으로 평균 구하기 
# 여기서 0은 첫번째 차원을 의미하고, 첫번째 차원은 행을 의미함
# 따라서 첫번째 차원을 제거하면서 계산을 함
# (2,2) 에서 첫번째 차원을 1로 만들어 (1,2)가 됨

# 1과 3의 평균을 구하고 2와 4의 평균을 구함

print(t.mean(dim = 0))

tensor([2., 3.])


## 3. sum() 함수

In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [23]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


4. max와 argmax
max는 원소의 최대값을, argmax는 최대값을 가진 인덱스를 반환함

In [24]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [25]:
t.max()

tensor(4.)

In [26]:
t.max(dim=0)
# 첫번째 차원을 제거한다는 의미
# 최대값은 [3 4]
# 이때 max에 dim 인자를 주면 argmax도 함께 return 하기때문

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [27]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [28]:
print(t.max(dim=1))
print(t.max(dim=-1))


torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## 4. 뷰 - 원소의 수 유지하면서 크기 변경 (중요함)
파이토치의 뷰는 넘파이에서 reshape와 같은 역할을 함

In [29]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [30]:
# 3차원 텐서에서 2차원 텐서로 변환

print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

# -1은 첫번째 차원은 파이토치에게 맡기겠다는 것 
# (2, 2, 3) -> (2 × 2, 3) -> (4, 3)

# 규칙
# view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 합니다.
# 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추합니다.

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [31]:
# 3차원에서 3차원으로 변경
# (2x2x3) = (? x 1 x 3) = 12 를 만족하게 하려면 ?는 4가 됨
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)


tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 5. squeeze - 1인 차원을 제거한다.

In [32]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [33]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## unsqueeze - 특정 위치에 1인 차원을 추가한다.


In [34]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [35]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [36]:
# view 에서도 똑같이 구현 가능
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [37]:
# -1은 인덱스상에서 마지막 차원을 의미함.
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### 7. 타입 캐스팅
텐서에는 자료형이 있음
예를 들면 64비트 부호가 있는 정수는 torch.LongTensor 가 있고
GPU 연산을 위한 자료형도 있는데 예를 들면 corch.cuda.FloatTensor가 있음

이때 타입을 변환하는걸 타입 캐스팅이라고 함


In [38]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)


tensor([1, 2, 3, 4])


In [39]:
# 텐서 뒤에 .float()를 붙이면 타입이 변경됨
print(lt.float())

tensor([1., 2., 3., 4.])


In [40]:
# 바이트 타입 텐서 선언
bt = torch.ByteTensor([True,True,False,True])
bt

tensor([1, 1, 0, 1], dtype=torch.uint8)

In [41]:
# 타입 변환해보기
print(bt.long())
print(bt.float())

tensor([1, 1, 0, 1])
tensor([1., 1., 0., 1.])


### 8. 연결하기(concatenate)
두 텐서를 연결하기 

In [42]:
# 2X2 텐서를 2개 만듬
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [43]:
# torch.cat 함수를 이용해 연결하기
# 이때 어느 차원을 늘린것인지 인자로 줄 수 있음
print(torch.cat([x,y],dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [44]:
print(torch.cat([x,y],dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### 9. 스태킹(stacking)
연결을 하는 또다른 방법으로 스택킹이 있음
연결보다 스태킹이 더편할 때가 있음

In [45]:
# 크기가 (2,)로 동일한 3개의 벡터를 만듬
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [46]:
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [47]:
# 벡터가 순차적으로 쌓여서 3X2 텐서가 된걸 볼 수 있음
# 스태킹은 아래의 연산을 축약하고 있음

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
# x,y,z는 (2,)크기를 갖는데 unsqueeze(0)으로 전부 (1,2)로 바꾸고
# cat로 연결해준것

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [48]:
# 두번째 차원이 증가하도록 쌓으라는 의미로 사용도 가능
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### 10. ones_like 와 zeros_like
 0으로 채워진 텐서, 1로 채워진 텐서


In [49]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [50]:
# 이 텐서에서 입력 크기는 동일하게 가면서 값을 1로 채우기
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [51]:
# 마찬가지로 0으로 채우기
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 11. in-place 연산(덮어쓰기 연산)

In [52]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [53]:
# 이렇게 하면 기존의 값은 바뀌지 않음
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [54]:
# 덮어쓰기를 하려면 연산 뒤에 _를 붙이면 기존 값에 덮어쓰기를 함
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
